name: 'Windows Build'

description: Build the project on Windows

inputs:
  compiler-version:
    default: 10
  python-version:
    required: false
    default: '3.10'

runs:
    using: "composite"
    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'

      - name: Install prerequisites
        shell: bash
        run: |
          pip3 install conan==1.64
      - name: Run conan
        shell: bash
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        shell: bash
        run: |
          cmake . -A x64 -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Archive Python Application
        uses: actions/upload-artifact@v4
        with:
          name: CosmoSimPy-windows-python${{ inputs.python-version }}
          path: build/lib/CosmoSimPy.*.pyd
      - name: Test
        shell: bash
        run: |
          pip3 install -r requirements.txt
          cp build/lib/CosmoSimPy.*.pyd CosmoSimPy/CosmoSim
          python3 CosmoSimPy/datagen.py
